DiscussionCategory.create!(:name => "General Jazz Discussion", :description => "Discussion of anything.")
DiscussionCategory.create!(:name => "Jazz Artists & Discography", :description => "Discussion of jazz musicians.", :discussable_type => "Musician")
DiscussionCategory.create!(:name => "Tunes & Composition", :description => "Discussion of tunes and composition.", :discussable_type => "Tune")
DiscussionCategory.create!(:name => "Chords & Voicings", :description => "Discussion of chords and voicings.", :discussable_type => "Chord", :discussable_type_2 => "Voicing")
DiscussionCategory.create!(:name => "Scales & Modes", :description => "Discussion of scales and modes.", :discussable_type => "Scale", :discussable_type_2 => "Mode")
DiscussionCategory.create!(:name => "Progressions & Form", :description => "Discussion of chord progressions and tune form.", :discussable_type => "Progression")
DiscussionCategory.create!(:name => "Concepts & Techniques", :description => "Discussion of concepts and techniques.", :discussable_type => "Concept")
DiscussionCategory.create!(:name => "Improvisation & Melodic Ideas", :description => "Discussion of improvisation and melodic ideas.")
